article: https://www.hackster.io/jakub-smejkal/turris-lcd-monitor-with-bigclown-1feff8
assembly:
  - name: BigClown LCD Module
  - name: BigClown Core Module
  - name: BigClown Mini Battery Module